"""Add_exercises_column

Revision ID: 28ad92f14f28
Revises: 64d0a33745d8
Create Date: 2026-02-12 07:12:39.666764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ad92f14f28'
down_revision: Union[str, None] = '64d0a33745d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('exercises', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'exercises')
    # ### end Alembic commands ###
