"""add_ondelete_cascades

Revision ID: 4c9a1d7e2b11
Revises: 2f31b5d9a6c1
Create Date: 2026-02-18

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "4c9a1d7e2b11"
down_revision: Union[str, None] = "2f31b5d9a6c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _is_postgres() -> bool:
    bind = op.get_bind()
    return bind is not None and bind.dialect.name == "postgresql"


def upgrade() -> None:
    # NOTE: SQLite cannot easily alter FK constraints in-place.
    # For Postgres we drop default-named constraints and recreate with ON DELETE.
    if not _is_postgres():
        return

    def _drop_fk_if_exists(table: str, constraint: str) -> None:
        # Alembic op.drop_constraint doesn't support IF EXISTS; production DBs may have
        # different autogenerated names depending on how schema was created.
        op.execute(f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {constraint}")

    # enrollments.user_id -> users.id (CASCADE)
    _drop_fk_if_exists("enrollments", "enrollments_user_id_fkey")
    op.create_foreign_key(
        "enrollments_user_id_fkey",
        "enrollments",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # enrollments.course_template_id -> course_templates.id (RESTRICT)
    _drop_fk_if_exists("enrollments", "enrollments_course_template_id_fkey")
    op.create_foreign_key(
        "enrollments_course_template_id_fkey",
        "enrollments",
        "course_templates",
        ["course_template_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # user_level_progress.enrollment_id -> enrollments.id (CASCADE)
    _drop_fk_if_exists("user_level_progress", "user_level_progress_enrollment_id_fkey")
    op.create_foreign_key(
        "user_level_progress_enrollment_id_fkey",
        "user_level_progress",
        "enrollments",
        ["enrollment_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # user_level_progress.level_template_id -> course_level_templates.id (RESTRICT)
    _drop_fk_if_exists("user_level_progress", "user_level_progress_level_template_id_fkey")
    op.create_foreign_key(
        "user_level_progress_level_template_id_fkey",
        "user_level_progress",
        "course_level_templates",
        ["level_template_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # generated_lessons.enrollment_id -> enrollments.id (CASCADE)
    _drop_fk_if_exists("generated_lessons", "generated_lessons_enrollment_id_fkey")
    op.create_foreign_key(
        "generated_lessons_enrollment_id_fkey",
        "generated_lessons",
        "enrollments",
        ["enrollment_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # generated_lessons.level_template_id -> course_level_templates.id (RESTRICT)
    _drop_fk_if_exists("generated_lessons", "generated_lessons_level_template_id_fkey")
    op.create_foreign_key(
        "generated_lessons_level_template_id_fkey",
        "generated_lessons",
        "course_level_templates",
        ["level_template_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # generated_vocabulary_items.generated_lesson_id -> generated_lessons.id (CASCADE)
    _drop_fk_if_exists(
        "generated_vocabulary_items",
        "generated_vocabulary_items_generated_lesson_id_fkey",
    )
    op.create_foreign_key(
        "generated_vocabulary_items_generated_lesson_id_fkey",
        "generated_vocabulary_items",
        "generated_lessons",
        ["generated_lesson_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # generated_vocabulary_items.user_lexeme_id -> user_lexemes.id (SET NULL)
    _drop_fk_if_exists(
        "generated_vocabulary_items",
        "generated_vocabulary_items_user_lexeme_id_fkey",
    )
    op.create_foreign_key(
        "generated_vocabulary_items_user_lexeme_id_fkey",
        "generated_vocabulary_items",
        "user_lexemes",
        ["user_lexeme_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # streaks.user_id -> users.id (CASCADE)
    _drop_fk_if_exists("streaks", "streaks_user_id_fkey")
    op.create_foreign_key(
        "streaks_user_id_fkey",
        "streaks",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # user_level_attempts.enrollment_id -> enrollments.id (CASCADE)
    _drop_fk_if_exists("user_level_attempts", "user_level_attempts_enrollment_id_fkey")
    op.create_foreign_key(
        "user_level_attempts_enrollment_id_fkey",
        "user_level_attempts",
        "enrollments",
        ["enrollment_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # user_level_attempts.level_template_id -> course_level_templates.id (RESTRICT)
    _drop_fk_if_exists("user_level_attempts", "user_level_attempts_level_template_id_fkey")
    op.create_foreign_key(
        "user_level_attempts_level_template_id_fkey",
        "user_level_attempts",
        "course_level_templates",
        ["level_template_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # user_level_attempts.progress_id -> user_level_progress.id (CASCADE)
    _drop_fk_if_exists("user_level_attempts", "user_level_attempts_progress_id_fkey")
    op.create_foreign_key(
        "user_level_attempts_progress_id_fkey",
        "user_level_attempts",
        "user_level_progress",
        ["progress_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # user_lexemes.user_id -> users.id (CASCADE)
    _drop_fk_if_exists("user_lexemes", "user_lexemes_user_id_fkey")
    op.create_foreign_key(
        "user_lexemes_user_id_fkey",
        "user_lexemes",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # user_lexemes.enrollment_id -> enrollments.id (SET NULL)
    _drop_fk_if_exists("user_lexemes", "user_lexemes_enrollment_id_fkey")
    op.create_foreign_key(
        "user_lexemes_enrollment_id_fkey",
        "user_lexemes",
        "enrollments",
        ["enrollment_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # user_lexemes.lexeme_id -> lexemes.id (CASCADE)
    _drop_fk_if_exists("user_lexemes", "user_lexemes_lexeme_id_fkey")
    op.create_foreign_key(
        "user_lexemes_lexeme_id_fkey",
        "user_lexemes",
        "lexemes",
        ["lexeme_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # lesson_lexemes.generated_lesson_id -> generated_lessons.id (CASCADE)
    _drop_fk_if_exists("lesson_lexemes", "lesson_lexemes_generated_lesson_id_fkey")
    op.create_foreign_key(
        "lesson_lexemes_generated_lesson_id_fkey",
        "lesson_lexemes",
        "generated_lessons",
        ["generated_lesson_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # lesson_lexemes.lexeme_id -> lexemes.id (CASCADE)
    _drop_fk_if_exists("lesson_lexemes", "lesson_lexemes_lexeme_id_fkey")
    op.create_foreign_key(
        "lesson_lexemes_lexeme_id_fkey",
        "lesson_lexemes",
        "lexemes",
        ["lexeme_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # lesson_lexemes.user_lexeme_id -> user_lexemes.id (SET NULL)
    _drop_fk_if_exists("lesson_lexemes", "lesson_lexemes_user_lexeme_id_fkey")
    op.create_foreign_key(
        "lesson_lexemes_user_lexeme_id_fkey",
        "lesson_lexemes",
        "user_lexemes",
        ["user_lexeme_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # course_section_templates.course_template_id -> course_templates.id (CASCADE)
    _drop_fk_if_exists(
        "course_section_templates",
        "course_section_templates_course_template_id_fkey",
    )
    op.create_foreign_key(
        "course_section_templates_course_template_id_fkey",
        "course_section_templates",
        "course_templates",
        ["course_template_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # course_unit_templates.section_template_id -> course_section_templates.id (CASCADE)
    _drop_fk_if_exists(
        "course_unit_templates",
        "course_unit_templates_section_template_id_fkey",
    )
    op.create_foreign_key(
        "course_unit_templates_section_template_id_fkey",
        "course_unit_templates",
        "course_section_templates",
        ["section_template_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # course_level_templates.unit_template_id -> course_unit_templates.id (CASCADE)
    _drop_fk_if_exists(
        "course_level_templates",
        "course_level_templates_unit_template_id_fkey",
    )
    op.create_foreign_key(
        "course_level_templates_unit_template_id_fkey",
        "course_level_templates",
        "course_unit_templates",
        ["unit_template_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    # Best-effort: don't attempt to revert FK actions.
    pass
