"""add_user_interests

Revision ID: 4ee2a3e318ee
Revises: e0320cad2ddc
Create Date: 2026-02-12 18:52:10.708722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee2a3e318ee'
down_revision: Union[str, None] = 'e0320cad2ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interests', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interests')
    # ### end Alembic commands ###
