"""Новая миграция

Revision ID: 57020216c680
Revises: 
Create Date: 2026-03-06 00:33:03.737889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.features.common.db import GUID


# revision identifiers, used by Alembic.
revision: str = '57020216c680'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_slug'), 'achievements', ['slug'], unique=True)
    op.create_table('ai_generation_events',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('generation_mode', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('repair_count', sa.Integer(), nullable=True),
    sa.Column('quality_status', sa.String(), nullable=True),
    sa.Column('error_codes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_cache_entries',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('prompt_hash', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_hash', name='uq_llm_cache_prompt_hash')
    )
    op.create_table('themes',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('theme_type', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('owner_user_id', GUID(), nullable=True),
    sa.Column('light_tokens', sa.JSON(), nullable=True),
    sa.Column('dark_tokens', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_themes_owner', 'themes', ['owner_user_id'], unique=False)
    op.create_index('ix_themes_type_public', 'themes', ['theme_type', 'is_public'], unique=False)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('last_ip', sa.String(), nullable=True),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('native_language', sa.String(), nullable=True),
    sa.Column('target_language', sa.String(), nullable=True),
    sa.Column('language_levels', sa.JSON(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('preferred_name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('ui_theme', sa.String(), nullable=True),
    sa.Column('selected_theme_id', GUID(), nullable=True),
    sa.Column('assistant_tone', sa.String(), nullable=True),
    sa.Column('assistant_verbosity', sa.Integer(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_foreign_key(
        'fk_themes_owner_user_id_users',
        'themes',
        'users',
        ['owner_user_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_users_selected_theme_id_themes',
        'users',
        'themes',
        ['selected_theme_id'],
        ['id'],
        ondelete='SET NULL',
    )

    op.create_table('characters',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.String(), nullable=False),
    sa.Column('style_prompt', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('greeting', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('voice_provider', sa.String(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('voice_settings', sa.JSON(), nullable=True),
    sa.Column('chat_settings', sa.JSON(), nullable=True),
    sa.Column('chat_theme_id', GUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_nsfw', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_theme_id'], ['themes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'slug', name='uq_character_owner_slug')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('created_ip', sa.String(), nullable=True),
    sa.Column('created_user_agent', sa.String(), nullable=True),
    sa.Column('created_app_version', sa.String(), nullable=True),
    sa.Column('last_ip', sa.String(), nullable=True),
    sa.Column('last_user_agent', sa.String(), nullable=True),
    sa.Column('last_app_version', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_device_id'), 'refresh_tokens', ['device_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_nsfw', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.String(length=512), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_uploads_owner_created', 'uploads', ['owner_user_id', 'created_at'], unique=False)
    op.create_index('ix_uploads_public_id', 'uploads', ['public_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('achievement_id', GUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('external_customer_id', sa.String(), nullable=True),
    sa.Column('external_subscription_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('character_id', GUID(), nullable=True),
    sa.Column('room_id', GUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('turns_count', sa.Integer(), nullable=False),
    sa.Column('user_turns_count', sa.Integer(), nullable=False),
    sa.Column('assistant_turns_count', sa.Integer(), nullable=False),
    sa.Column('last_summary_at_turn', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('author_user_id', GUID(), nullable=False),
    sa.Column('character_id', GUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_author_created', 'posts', ['author_user_id', 'created_at'], unique=False)
    op.create_index('ix_posts_public_created', 'posts', ['is_public', 'created_at'], unique=False)
    op.create_table('room_participants',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('room_id', GUID(), nullable=False),
    sa.Column('character_id', GUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'character_id', name='uq_room_character')
    )
    op.create_table('chat_session_summaries',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('up_to_turn_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_summary_session_created', 'chat_session_summaries', ['session_id', 'created_at'], unique=False)
    op.create_table('chat_turns',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('character_id', GUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'turn_index', name='uq_chat_turn_session_index')
    )
    op.create_index('ix_chat_turns_session_created', 'chat_turns', ['session_id', 'created_at'], unique=False)
    op.create_table('memory_items',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('character_id', GUID(), nullable=True),
    sa.Column('room_id', GUID(), nullable=True),
    sa.Column('session_id', GUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_owner_character', 'memory_items', ['owner_user_id', 'character_id'], unique=False)
    op.create_index('ix_memory_owner_created', 'memory_items', ['owner_user_id', 'created_at'], unique=False)
    op.create_table('post_comments',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('post_id', GUID(), nullable=False),
    sa.Column('author_user_id', GUID(), nullable=False),
    sa.Column('parent_id', GUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_comments_author_created', 'post_comments', ['author_user_id', 'created_at'], unique=False)
    op.create_index('ix_post_comments_post_created', 'post_comments', ['post_id', 'created_at'], unique=False)
    op.create_table('post_likes',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('post_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_like')
    )
    op.create_index('ix_post_likes_post_created', 'post_likes', ['post_id', 'created_at'], unique=False)
    op.create_index('ix_post_likes_user_created', 'post_likes', ['user_id', 'created_at'], unique=False)
    op.create_table('moderation_events',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('owner_user_id', GUID(), nullable=False),
    sa.Column('session_id', GUID(), nullable=True),
    sa.Column('turn_id', GUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turn_id'], ['chat_turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderation_owner_created', 'moderation_events', ['owner_user_id', 'created_at'], unique=False)
    op.create_index('ix_moderation_session_created', 'moderation_events', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_moderation_session_created', table_name='moderation_events')
    op.drop_index('ix_moderation_owner_created', table_name='moderation_events')
    op.drop_table('moderation_events')
    op.drop_index('ix_post_likes_user_created', table_name='post_likes')
    op.drop_index('ix_post_likes_post_created', table_name='post_likes')
    op.drop_table('post_likes')
    op.drop_index('ix_post_comments_post_created', table_name='post_comments')
    op.drop_index('ix_post_comments_author_created', table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_index('ix_memory_owner_created', table_name='memory_items')
    op.drop_index('ix_memory_owner_character', table_name='memory_items')
    op.drop_table('memory_items')
    op.drop_index('ix_chat_turns_session_created', table_name='chat_turns')
    op.drop_table('chat_turns')
    op.drop_index('ix_chat_summary_session_created', table_name='chat_session_summaries')
    op.drop_table('chat_session_summaries')
    op.drop_table('room_participants')
    op.drop_index('ix_posts_public_created', table_name='posts')
    op.drop_index('ix_posts_author_created', table_name='posts')
    op.drop_table('posts')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index('ix_uploads_public_id', table_name='uploads')
    op.drop_index('ix_uploads_owner_created', table_name='uploads')
    op.drop_table('uploads')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_device_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('characters')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_themes_type_public', table_name='themes')
    op.drop_index('ix_themes_owner', table_name='themes')
    op.drop_table('themes')
    op.drop_table('llm_cache_entries')
    op.drop_table('ai_generation_events')
    op.drop_index(op.f('ix_achievements_slug'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
