"""Add_user_languages

Revision ID: 64d0a33745d8
Revises: d05f5edc8bc4
Create Date: 2026-02-12 06:06:06.879562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d0a33745d8'
down_revision: Union[str, None] = 'd05f5edc8bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('native_language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('native_language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('target_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'target_language')
    op.drop_column('users', 'native_language')
    op.drop_column('lessons', 'native_language')
    # ### end Alembic commands ###
