"""add_path_tables

Revision ID: e0320cad2ddc
Revises: 28ad92f14f28
Create Date: 2026-02-12 18:03:01.973142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.custom_types


# revision identifiers, used by Alembic.
revision: str = 'e0320cad2ddc'
down_revision: Union[str, None] = '28ad92f14f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', app.models.custom_types.GUID(), nullable=False),
    sa.Column('user_id', app.models.custom_types.GUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', app.models.custom_types.GUID(), nullable=False),
    sa.Column('section_id', app.models.custom_types.GUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levels',
    sa.Column('id', app.models.custom_types.GUID(), nullable=False),
    sa.Column('unit_id', app.models.custom_types.GUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('levels')
    op.drop_table('units')
    op.drop_table('sections')
    # ### end Alembic commands ###
